{% set name = "cgns" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name|upper }}/{{ name|upper }}/archive/v{{ version }}.tar.gz
  sha256: 6372196caf25b27d38cf6f056258cb0bdd45757f49d9c59372b6dbbddb1e05da
  patches:
    - if-block.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  host:
    - zlib
    - hdf5 =1.8
  run:
    - zlib
    - hdf5 =1.8

test:
  commands:
    - cgnscheck

about:
  home: http://cgns.org
  license: Zlib
  license_file: LICENSE
  summary: 'CFD General Notation System (CGNS)'
  description: |
    The CFD General Notation System (CGNS) provides a standard for
    recording and recovering computer data associated with the
    numerical solution of fluid dynamics equations.
  doc_url: http://cgns.github.io/CGNS_docs_current/index.html
  dev_url: https://github.com/CGNS/CGNS

extra:
  recipe-maintainers:
    - mdpiper
